name: upload to curseforge
on:
  workflow_dispatch:
  push:
    branches:
    - master
    tags:
    - '*'
    paths-ignore:
    - ".github/**"
    - "README.md"
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clone project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Package and release
        uses: BigWigsMods/packager@v2
        with:
          args: -p 1088091
